# Generated by Django 6.0.5 on 2026-05-11 04:41

from django.db import migrations, models


# 迁移类：声明本次数据库结构变更和依赖关系。
class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_contract_responsible_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='invoicerecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='金额'),
        ),
    ]
