# Generated by Django 6.0.5 on 2026-05-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0018_alter_contract_amount_alter_invoicerecord_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='image_root_path',
            field=models.CharField(blank=True, default='C:\\Users\\YF\\Desktop\\ocr_image_renamer\\整理后图片', max_length=500, verbose_name='图片保存位置'),
        ),
    ]
