# Generated by Django 6.0.5 on 2026-05-12 00:38

from django.db import migrations, models


# 迁移类：声明本次数据库结构变更和依赖关系。
class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0019_appsetting_image_root_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='original_contract_folder',
            field=models.CharField(blank=True, max_length=100, verbose_name='原合同文件夹'),
        ),
        migrations.AddField(
            model_name='contract',
            name='original_contract_inner_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='文件夹内编号'),
        ),
    ]
