# Generated by Codex on 2026-05-12.

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0021_update_invoice_status_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsetting",
            name="preview_root_path",
            field=models.CharField(
                blank=True,
                default=contracts.models.default_preview_root_path,
                max_length=500,
                verbose_name="文件预览位置",
            ),
        ),
    ]
