# Generated by Django 6.0.5 on 2026-05-13 06:07

import contracts.models
import django.db.models.deletion
import django.utils.timezone
from pathlib import PurePath
from django.db import migrations, models


def create_initial_file_versions(apps, schema_editor):
    model_pairs = [
        ("InvoiceRecord", "InvoiceRecordFileVersion"),
        ("PaymentRecord", "PaymentRecordFileVersion"),
        ("MaintenanceRecord", "MaintenanceRecordFileVersion"),
    ]
    for record_model_name, version_model_name in model_pairs:
        record_model = apps.get_model("contracts", record_model_name)
        version_model = apps.get_model("contracts", version_model_name)
        for record in record_model.objects.exclude(file=""):
            file_name = getattr(record.file, "name", "") or ""
            if not file_name:
                continue
            version_model.objects.create(
                record=record,
                file=file_name,
                original_name=PurePath(file_name).name,
                created_at=getattr(record, "updated_at", None) or getattr(record, "created_at", None) or django.utils.timezone.now(),
            )


def delete_initial_file_versions(apps, schema_editor):
    for version_model_name in ("InvoiceRecordFileVersion", "PaymentRecordFileVersion", "MaintenanceRecordFileVersion"):
        version_model = apps.get_model("contracts", version_model_name)
        version_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0027_operationlog_content_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRecordFileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=contracts.models.project_file_upload_path, verbose_name='附件')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='原文件名')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_versions', to='contracts.invoicerecord', verbose_name='所属开票记录')),
            ],
            options={
                'verbose_name': '开票附件版本',
                'verbose_name_plural': '开票附件版本',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecordFileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=contracts.models.project_file_upload_path, verbose_name='附件')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='原文件名')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_versions', to='contracts.maintenancerecord', verbose_name='所属项目记录')),
            ],
            options={
                'verbose_name': '项目记录附件版本',
                'verbose_name_plural': '项目记录附件版本',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecordFileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=contracts.models.project_file_upload_path, verbose_name='附件')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='原文件名')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_versions', to='contracts.paymentrecord', verbose_name='所属收票记录')),
            ],
            options={
                'verbose_name': '收票附件版本',
                'verbose_name_plural': '收票附件版本',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RunPython(create_initial_file_versions, delete_initial_file_versions),
    ]
