# Generated by Django 6.0.5 on 2026-05-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0028_invoicerecordfileversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='allow_partial_import_with_errors',
            field=models.BooleanField(default=False, verbose_name='Excel 导入存在错误时仍导入通过行'),
        ),
    ]
