# Generated by Django 6.0.5 on 2026-05-13 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0029_appsetting_allow_partial_import_with_errors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsetting',
            name='delete_source_file',
        ),
    ]
