# Generated by Django 6.0.5 on 2026-05-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0032_rename_storage_location_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='is_undone',
            field=models.BooleanField(default=False, verbose_name='是否已撤回'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='undone_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='撤回时间'),
        ),
    ]
