# Generated by Django 6.0.5 on 2026-05-15 03:53

from django.db import migrations, models


def move_other_contract_type_to_default(apps, _schema_editor):
    Contract = apps.get_model("contracts", "Contract")
    Contract.objects.filter(contract_type="其他").update(contract_type="维保")


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0033_operationlog_is_undone_operationlog_undone_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='record_position_number',
            field=models.CharField(blank=True, default='000', max_length=100, verbose_name='位置编号'),
        ),
        migrations.RunPython(move_other_contract_type_to_default, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('维保', '维保'), ('评估', '评估'), ('检测', '检测'), ('改造', '改造'), ('新建', '新建')], default='维保', max_length=20, verbose_name='合同类型'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='storage_location_number',
            field=models.CharField(blank=True, default='00', max_length=100, verbose_name='位置编号'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='storage_location_number',
            field=models.CharField(blank=True, default='00', max_length=100, verbose_name='分册编号'),
        ),
    ]
