# Generated by Django 6.0.5 on 2026-05-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0034_maintenancerecord_record_position_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='storage_location_number',
            field=models.CharField(blank=True, default='01', max_length=100, verbose_name='分册编号'),
        ),
    ]
