# Generated by Codex on 2026-05-16

from django.db import migrations, models


def populate_month_number(apps, schema_editor):
    MaintenanceRecord = apps.get_model("contracts", "MaintenanceRecord")
    for record in MaintenanceRecord.objects.all().only("pk", "record_date", "month_number"):
        record.month_number = f"{record.record_date.month:02d}" if record.record_date else "01"
        record.save(update_fields=["month_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0035_alter_maintenancerecord_storage_location_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancerecord",
            name="month_number",
            field=models.CharField(blank=True, default="01", max_length=2, verbose_name="月份编号"),
        ),
        migrations.RunPython(populate_month_number, migrations.RunPython.noop),
    ]
