# Generated by Codex on 2026-05-16

from django.db import migrations


def refresh_month_number(apps, schema_editor):
    MaintenanceRecord = apps.get_model("contracts", "MaintenanceRecord")
    for record in MaintenanceRecord.objects.all().only("pk", "record_date", "month_number"):
        record.month_number = f"{record.record_date.month:02d}" if record.record_date else "01"
        record.save(update_fields=["month_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0036_maintenancerecord_month_number"),
    ]

    operations = [
        migrations.RunPython(refresh_month_number, migrations.RunPython.noop),
    ]
