# Generated by Codex on 2026-05-16

from django.db import migrations, models


def populate_date_number(apps, schema_editor):
    MaintenanceRecord = apps.get_model("contracts", "MaintenanceRecord")
    for record in MaintenanceRecord.objects.all().only("pk", "record_date", "date_number"):
        record.date_number = f"{str(record.record_date.year)[-2:]}{record.record_date.month:02d}" if record.record_date else "0000"
        record.save(update_fields=["date_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0037_refresh_maintenancerecord_month_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="maintenancerecord",
            old_name="month_number",
            new_name="date_number",
        ),
        migrations.AlterField(
            model_name="maintenancerecord",
            name="date_number",
            field=models.CharField(blank=True, default="0000", max_length=4, verbose_name="年月编号"),
        ),
        migrations.RunPython(populate_date_number, migrations.RunPython.noop),
    ]
