# Generated by Codex on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0038_rename_month_number_to_date_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsetting",
            name="allow_force_contract_import_update",
            field=models.BooleanField(default=False, verbose_name="合同导入允许强行修改匹配行"),
        ),
    ]
