# Generated by Codex on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0039_appsetting_allow_force_contract_import_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsetting",
            name="record_position_cabinet_number",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="记录位置柜号"),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="record_position_column_count",
            field=models.PositiveSmallIntegerField(default=12, verbose_name="记录位置栏目量"),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="record_position_column_capacity",
            field=models.PositiveSmallIntegerField(default=10, verbose_name="记录位置栏目存放数"),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="record_position_start_file_number",
            field=models.PositiveIntegerField(default=3441, verbose_name="记录位置起始界限点"),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="record_position_start_column",
            field=models.PositiveSmallIntegerField(default=5, verbose_name="记录位置存放栏目"),
        ),
        migrations.AddField(
            model_name="appsetting",
            name="record_position_direction",
            field=models.CharField(
                choices=[("increment", "递增1"), ("decrement", "递减1")],
                default="decrement",
                max_length=20,
                verbose_name="记录位置存放逻辑",
            ),
        ),
    ]
