# Generated by Codex on 2026-05-16

from django.db import migrations, models


def normalize_number_part(value, width):
    digits = "".join(ch for ch in str(value or "").strip() if ch.isdigit())
    return digits[-width:].zfill(width) if digits else ""


def populate_record_real_sequence(apps, schema_editor):
    AppSetting = apps.get_model("contracts", "AppSetting")
    Contract = apps.get_model("contracts", "Contract")
    MaintenanceRecord = apps.get_model("contracts", "MaintenanceRecord")
    setting = AppSetting.objects.filter(pk=1).first()
    start_file = int(getattr(setting, "record_position_start_file_number", 3441) or 3441)
    contracts = {contract.pk: contract for contract in Contract.objects.all()}
    for record in MaintenanceRecord.objects.all().iterator():
        contract = contracts.get(record.contract_id)
        file_number = normalize_number_part(getattr(contract, "original_contract_inner_number", ""), 5) if contract else ""
        volume_number = normalize_number_part(record.storage_location_number, 2) or "01"
        if file_number:
            record.real_sequence_number = int(file_number) - start_file + int(volume_number)
            record.save(update_fields=["real_sequence_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0040_appsetting_record_position_auto_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsetting",
            name="record_position_enable_insert_sort",
            field=models.BooleanField(default=False, verbose_name="记录位置启用插入重排序"),
        ),
        migrations.AddField(
            model_name="maintenancerecord",
            name="real_sequence_number",
            field=models.IntegerField(default=0, verbose_name="实序编号"),
        ),
        migrations.AlterField(
            model_name="maintenancerecord",
            name="record_position_number",
            field=models.CharField(blank=True, default="0000", max_length=100, verbose_name="位置编号"),
        ),
        migrations.RunPython(populate_record_real_sequence, migrations.RunPython.noop),
    ]
