# Generated by Codex on 2026-05-16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def normalize_number_part(value, width):
    digits = "".join(ch for ch in str(value or "").strip() if ch.isdigit())
    return digits[-width:].zfill(width) if digits else ""


def normalize_volume_number(value):
    return normalize_number_part(value, 2) or "01"


def position_number_from_sequence(sequence_number, setting):
    sequence_number = int(sequence_number or 0)
    if not sequence_number:
        return "0000"
    capacity = max(int(getattr(setting, "record_position_column_capacity", 1) or 1), 1)
    column_count = max(int(getattr(setting, "record_position_column_count", 1) or 1), 1)
    start_column = min(max(int(getattr(setting, "record_position_start_column", 1) or 1), 1), column_count)
    cabinet = max(int(getattr(setting, "record_position_cabinet_number", 1) or 1), 1)
    start_file = max(int(getattr(setting, "record_position_start_file_number", 1) or 1), 1)
    direction = getattr(setting, "record_position_direction", "decrement")
    offset = sequence_number - start_file + 1
    if offset > 0:
        column_steps = (offset - 1) // capacity
        forward_direction = direction
        cabinet_step = 1
    else:
        column_steps = ((-offset - 1) // capacity) + 1
        forward_direction = "decrement" if direction == "increment" else "increment"
        cabinet_step = -1
    if forward_direction == "increment":
        column_index = start_column - 1 + column_steps
        cabinet += cabinet_step * (column_index // column_count)
        column = (column_index % column_count) + 1
    else:
        column_index = start_column - 1 - column_steps
        wraps = ((-column_index - 1) // column_count + 1) if column_index < 0 else 0
        cabinet += cabinet_step * wraps
        column = (column_index % column_count) + 1
    return f"{max(cabinet, 1):02d}{column:02d}"


def populate_volume_sequences(apps, schema_editor):
    AppSetting = apps.get_model("contracts", "AppSetting")
    Contract = apps.get_model("contracts", "Contract")
    MaintenanceRecord = apps.get_model("contracts", "MaintenanceRecord")
    MaintenanceRecordVolumeSequence = apps.get_model("contracts", "MaintenanceRecordVolumeSequence")
    setting = AppSetting.objects.filter(pk=1).first() or AppSetting()
    start_file = max(int(getattr(setting, "record_position_start_file_number", 1) or 1), 1)
    contracts = {contract.pk: contract for contract in Contract.objects.all()}
    sequences = {}
    for record in MaintenanceRecord.objects.order_by("id"):
        volume = normalize_volume_number(record.storage_location_number)
        key = (record.contract_id, volume)
        sequence = sequences.get(key)
        if sequence is None:
            contract = contracts.get(record.contract_id)
            file_number = normalize_number_part(getattr(contract, "original_contract_inner_number", ""), 5) if contract else ""
            old_sequence = int(getattr(record, "real_sequence_number", 0) or 0)
            if volume == "01" and file_number:
                real_sequence = int(file_number)
            elif old_sequence:
                real_sequence = start_file + old_sequence - 1
            elif file_number:
                real_sequence = int(file_number) + int(volume) - 1
            else:
                real_sequence = 0
            sequence = MaintenanceRecordVolumeSequence.objects.create(
                contract_id=record.contract_id,
                storage_location_number=volume,
                real_sequence_number=real_sequence,
            )
            sequences[key] = sequence
        record.storage_location_number = volume
        record.record_position_number = position_number_from_sequence(sequence.real_sequence_number, setting)
        record.save(update_fields=["storage_location_number", "record_position_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0041_record_real_sequence_and_insert_sort"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRecordVolumeSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("storage_location_number", models.CharField(blank=True, default="01", max_length=100, verbose_name="分册编号")),
                ("real_sequence_number", models.IntegerField(default=0, verbose_name="实序编号")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("contract", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="record_volume_sequences", to="contracts.contract", verbose_name="所属合同")),
            ],
            options={
                "verbose_name": "项目记录分册实序",
                "verbose_name_plural": "项目记录分册实序",
                "ordering": ["real_sequence_number", "contract_id", "storage_location_number"],
                "unique_together": {("contract", "storage_location_number")},
            },
        ),
        migrations.RunPython(populate_volume_sequences, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="maintenancerecord",
            name="real_sequence_number",
        ),
    ]
