# Generated by Django 6.0.5 on 2026-05-16 14:04

import django.db.models.deletion
from django.db import migrations, models


def position_number_from_sequence(sequence_number, setting):
    sequence_number = int(sequence_number or 0)
    if not sequence_number:
        return "0000"
    capacity = max(int(getattr(setting, "record_position_column_capacity", 1) or 1), 1)
    column_count = max(int(getattr(setting, "record_position_column_count", 1) or 1), 1)
    start_column = min(max(int(getattr(setting, "record_position_start_column", 1) or 1), 1), column_count)
    cabinet = max(int(getattr(setting, "record_position_cabinet_number", 1) or 1), 1)
    start_file = max(int(getattr(setting, "record_position_start_file_number", 1) or 1), 1)
    direction = getattr(setting, "record_position_direction", "decrement")
    offset = sequence_number - start_file + 1
    if offset > 0:
        column_steps = (offset - 1) // capacity
        forward_direction = direction
        cabinet_step = 1
    else:
        column_steps = ((-offset - 1) // capacity) + 1
        forward_direction = "decrement" if direction == "increment" else "increment"
        cabinet_step = -1
    if forward_direction == "increment":
        column_index = start_column - 1 + column_steps
        cabinet += cabinet_step * (column_index // column_count)
        column = (column_index % column_count) + 1
    else:
        column_index = start_column - 1 - column_steps
        wraps = ((-column_index - 1) // column_count + 1) if column_index < 0 else 0
        cabinet += cabinet_step * wraps
        column = (column_index % column_count) + 1
    return f"{max(cabinet, 1):02d}{column:02d}"


def populate_shelf_position_numbers(apps, schema_editor):
    AppSetting = apps.get_model("contracts", "AppSetting")
    MaintenanceRecordVolumeSequence = apps.get_model("contracts", "MaintenanceRecordVolumeSequence")
    setting = AppSetting.objects.filter(pk=1).first() or AppSetting()
    for sequence in MaintenanceRecordVolumeSequence.objects.order_by("id"):
        sequence.shelf_position_number = position_number_from_sequence(sequence.real_sequence_number, setting)
        sequence.save(update_fields=["shelf_position_number"])


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0042_record_volume_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='record_position_end_cabinet_number',
            field=models.PositiveSmallIntegerField(default=99, verbose_name='记录位置终止柜号'),
        ),
        migrations.AddField(
            model_name='maintenancerecordvolumesequence',
            name='shelf_position_number',
            field=models.CharField(blank=True, default='0000', max_length=100, verbose_name='排位'),
        ),
        migrations.AlterField(
            model_name='maintenancerecordvolumesequence',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_volume_sequences', to='contracts.contract', verbose_name='所属合同'),
        ),
        migrations.RunPython(populate_shelf_position_numbers, migrations.RunPython.noop),
    ]
