# Generated by Django 6.0.5 on 2026-05-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0043_appsetting_record_position_end_cabinet_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='record_position_reserved_slots',
            field=models.TextField(blank=True, verbose_name='记录位置预留排位'),
        ),
        migrations.AddField(
            model_name='maintenancerecordvolumesequence',
            name='is_reserved',
            field=models.BooleanField(default=False, verbose_name='是否预留'),
        ),
    ]
