# Generated by Django 6.0.5 on 2026-05-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0045_refresh_volume_sequence_shelf_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='record_position_force_empty_slot',
            field=models.BooleanField(default=False, verbose_name='记录位置强制空排位'),
        ),
    ]
