# Generated by Django 6.0.5 on 2026-05-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0047_refresh_maintenance_record_position_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='record_position_number',
            field=models.CharField(blank=True, default='000000', max_length=100, verbose_name='位置编号'),
        ),
        migrations.AlterField(
            model_name='maintenancerecordvolumesequence',
            name='shelf_position_number',
            field=models.CharField(blank=True, default='000000', max_length=100, verbose_name='排位'),
        ),
    ]
