# Generated by Django 6.0.5 on 2026-05-17 05:35

from django.db import migrations, models


def normalize_contract_storage_location_numbers(apps, schema_editor):
    Contract = apps.get_model("contracts", "Contract")
    for contract in Contract.objects.all().only("id", "storage_location_number"):
        digits = "".join(ch for ch in str(contract.storage_location_number or "") if ch.isdigit())
        normalized = digits[-3:].zfill(3) if digits else "000"
        if contract.storage_location_number != normalized:
            contract.storage_location_number = normalized
            contract.save(update_fields=["storage_location_number"])


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0048_alter_maintenancerecord_record_position_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='storage_location_number',
            field=models.CharField(blank=True, default='000', max_length=100, verbose_name='位置编号'),
        ),
        migrations.RunPython(normalize_contract_storage_location_numbers, migrations.RunPython.noop),
    ]
