# Generated by Django 6.0.5 on 2026-05-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0051_maintenancerecordvolumesequence_released_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsetting',
            name='record_position_column_capacity',
            field=models.CharField(default='10', max_length=100, verbose_name='记录位置栏目存放数'),
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='record_position_start_file_number',
            field=models.CharField(default='3441', max_length=100, verbose_name='记录位置起始界限点'),
        ),
    ]
