# Generated by Codex on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0052_alter_appsetting_record_position_column_capacity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="storage_mode",
            field=models.CharField(
                choices=[("文件夹", "文件夹"), ("仅文档", "仅文档")],
                default="文件夹",
                max_length=20,
                verbose_name="保存模式",
            ),
        ),
    ]
