# Generated by Codex on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0053_contract_storage_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="document_status",
            field=models.CharField(
                choices=[("进行中", "进行中"), ("已完结", "已完结")],
                default="进行中",
                max_length=20,
                verbose_name="仅文档状态",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="document_completed_date",
            field=models.DateField(blank=True, null=True, verbose_name="仅文档完结日期"),
        ),
    ]
