# Generated by Django 6.0.5 on 2026-05-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0054_contract_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='reverse_contract_file_number_generation',
            field=models.BooleanField(default=False, verbose_name='新增合同反向生成文件编号'),
        ),
    ]
