# Generated by Django 6.0.5 on 2026-05-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0055_appsetting_reverse_contract_file_number_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='shared_record_volume_contract_types',
            field=models.TextField(blank=True, verbose_name='共享分册合同类型'),
        ),
    ]
