# Generated by Codex on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0056_appsetting_shared_record_volume_contract_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsetting",
            name="specified_deadline_contract_types",
            field=models.TextField(blank=True, verbose_name="指定日期合同类型"),
        ),
    ]
