# Generated by Codex on 2026-05-19

from django.db import migrations


# 解析用 / 分隔的正整数配置，空值时使用默认回退值。
def slash_numbers(value, fallback):
    numbers = []
    for part in str(value or "").split("/"):
        part = part.strip()
        if part.isdigit() and int(part) > 0:
            numbers.append(int(part))
    return numbers or [fallback]


# 按起点、栏目数和方向计算向后推进后的柜号与栏目。
def column_from_steps(column_steps, start_cabinet, start_column, column_count, direction):
    if direction == "increment":
        first_cabinet_columns = max(column_count - start_column + 1, 0)
        if column_steps < first_cabinet_columns:
            return start_cabinet, start_column + column_steps
        remaining_steps = column_steps - first_cabinet_columns
        return start_cabinet + 1 + (remaining_steps // column_count), (remaining_steps % column_count) + 1
    first_cabinet_columns = max(start_column, 0)
    if column_steps < first_cabinet_columns:
        return start_cabinet, start_column - column_steps
    remaining_steps = column_steps - first_cabinet_columns
    return start_cabinet + 1 + (remaining_steps // column_count), column_count - (remaining_steps % column_count)


# 按起点、栏目数和方向计算起始界限点之前的柜号与栏目。
def column_before_start(column_steps, start_cabinet, start_column, column_count, direction):
    if direction == "increment":
        first_cabinet_columns = max(start_column - 1, 0)
        if column_steps <= first_cabinet_columns:
            return start_cabinet, start_column - column_steps
        remaining_steps = column_steps - first_cabinet_columns - 1
        return start_cabinet - 1 - (remaining_steps // column_count), column_count - (remaining_steps % column_count)
    first_cabinet_columns = max(column_count - start_column, 0)
    if column_steps <= first_cabinet_columns:
        return start_cabinet, start_column + column_steps
    remaining_steps = column_steps - first_cabinet_columns - 1
    return start_cabinet - 1 - (remaining_steps // column_count), (remaining_steps % column_count) + 1


# 根据系统设置生成每个起始界限点对应的容量和锚点。
def generation_tiers(setting):
    start_files = slash_numbers(getattr(setting, "record_position_start_file_number", "1"), 1)
    capacities = slash_numbers(getattr(setting, "record_position_column_capacity", "1"), 1)
    while len(capacities) < len(start_files):
        capacities.append(capacities[-1])
    tiers = [
        {"start_file": start_file, "capacity": max(capacities[index], 1)}
        for index, start_file in enumerate(start_files)
    ]
    tiers = sorted(tiers, key=lambda item: item["start_file"], reverse=True)
    column_count = max(int(getattr(setting, "record_position_column_count", 1) or 1), 1)
    start_cabinet = max(int(getattr(setting, "record_position_cabinet_number", 1) or 1), 1)
    start_column = min(max(int(getattr(setting, "record_position_start_column", 1) or 1), 1), column_count)
    anchor_cabinet = start_cabinet
    anchor_column = start_column
    previous_start_file = None
    for tier in tiers:
        if previous_start_file is not None:
            sequence_delta = max(int(previous_start_file) - int(tier["start_file"]), 0)
            capacity = max(int(tier["capacity"]), 1)
            column_delta = (sequence_delta + capacity - 1) // capacity
            anchor_cabinet, anchor_column = column_before_start(
                column_delta,
                anchor_cabinet,
                anchor_column,
                column_count,
                getattr(setting, "record_position_direction", "decrement") or "decrement",
            )
        tier["start_cabinet"] = anchor_cabinet
        tier["start_column"] = anchor_column
        previous_start_file = tier["start_file"]
    return tiers


# 为实序编号选择对应的起始界限点分段。
def tier_for_sequence(sequence_number, tiers):
    sequence_number = int(sequence_number or 0)
    for tier in tiers:
        if sequence_number >= int(tier["start_file"]):
            return tier
    return tiers[-1] if tiers else None


# 将实序编号换算为六位排位编号。
def shelf_position_number_from_sequence(sequence_number, setting):
    sequence_number = int(sequence_number or 0)
    if not sequence_number:
        return "000000"
    tiers = generation_tiers(setting)
    tier = tier_for_sequence(sequence_number, tiers)
    if tier is None:
        return "000000"
    capacity = max(int(tier.get("capacity") or 1), 1)
    column_count = max(int(getattr(setting, "record_position_column_count", 1) or 1), 1)
    start_column = min(max(int(tier.get("start_column") or getattr(setting, "record_position_start_column", 1) or 1), 1), column_count)
    start_cabinet = max(int(tier.get("start_cabinet") or getattr(setting, "record_position_cabinet_number", 1) or 1), 1)
    start_file = int(tier.get("start_file") or 1)
    direction = getattr(setting, "record_position_direction", "decrement") or "decrement"
    sequence_offset = sequence_number - start_file + 1
    if sequence_offset > 0:
        column_steps = (sequence_offset - 1) // capacity
        rank = ((sequence_offset - 1) % capacity) + 1
        cabinet, column = column_from_steps(column_steps, start_cabinet, start_column, column_count, direction)
    else:
        distance_before_start = start_file - sequence_number
        column_steps = ((distance_before_start - 1) // capacity) + 1
        rank = capacity - ((distance_before_start - 1) % capacity)
        cabinet, column = column_before_start(column_steps, start_cabinet, start_column, column_count, direction)
    return f"{max(cabinet, 1):02d}{column:02d}{rank:02d}"


# 刷新分册实序和项目记录上的排位编号，修复界限点边界计算结果。
def refresh_record_positions(apps, schema_editor):
    AppSetting = apps.get_model("contracts", "AppSetting")
    MaintenanceRecord = apps.get_model("contracts", "MaintenanceRecord")
    MaintenanceRecordVolumeSequence = apps.get_model("contracts", "MaintenanceRecordVolumeSequence")
    setting = AppSetting.objects.filter(pk=1).first() or AppSetting()
    for sequence in MaintenanceRecordVolumeSequence.objects.exclude(real_sequence_number=0).order_by("id"):
        position_number = shelf_position_number_from_sequence(sequence.real_sequence_number, setting)
        if sequence.shelf_position_number != position_number:
            sequence.shelf_position_number = position_number
            sequence.save(update_fields=["shelf_position_number"])
        if sequence.contract_id:
            MaintenanceRecord.objects.filter(
                contract_id=sequence.contract_id,
                storage_location_number=sequence.storage_location_number,
            ).exclude(record_position_number=position_number).update(record_position_number=position_number)


# 迁移类：执行一次性排位刷新数据迁移。
class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0057_appsetting_specified_deadline_contract_types"),
    ]

    operations = [
        migrations.RunPython(refresh_record_positions, migrations.RunPython.noop),
    ]
